import{a as b,i as L,S}from"./assets/vendor-DnVuFECx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const w="https://pixabay.com/api/",q="48986485-6ea1696c08190fb3e366663c0";async function v(e,t=1,i=40){try{return(await b.get(w,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:i}})).data}catch(n){throw console.error("Error fetching images:",n),n}}function $(e,t){if(!e||e.length===0){f("No images found!");return}const i=e.map(({webformatURL:n,largeImageURL:r,tags:o,likes:c,views:h,comments:m,downloads:g})=>`
      <a class="gallery-item" href="${r}" data-title="${o}">
        <img src="${n}" alt="${o}" loading="lazy"/>
        <div class="info">
          <p><b>Likes:</b> ${c}</p>
          <p><b>Views:</b> ${h}</p>
          <p><b>Comments:</b> ${m}</p>
          <p><b>Downloads:</b> ${g}</p>
        </div>
      </a>
    `).join("");t.insertAdjacentHTML("beforeend",i)}function E(e){e.innerHTML=""}function f(e,t="topRight"){try{L.show({message:e,position:t,timeout:3e3})}catch(i){console.error("Error displaying notification:",i)}}function P(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function I(e){e.style.display="block"}function M(e){e.style.display="none"}let y="",s=1,u=0;const d=document.querySelector(".form"),l=document.querySelector(".gallery"),a=document.querySelector(".load-more");document.querySelector(".loader");l||console.error("❌ Ошибка: Элемент '.gallery' не найден!");const O=new S(".gallery a",{captionsData:"alt",captionDelay:250});d==null||d.addEventListener("submit",A);a==null||a.addEventListener("click",N);function A(e){e.preventDefault();const t=e.currentTarget.elements.query;if(!t){console.error("❌ Поле ввода не найдено!");return}y=t.value.trim(),y&&(H(),p())}function H(){if(s=1,u=0,!l){console.error("❌ Ошибка: Невозможно очистить, так как gallery = undefined.");return}console.log("gallery:",l),E(l),D()}function N(){s++,p()}async function p(){I();try{const{hits:e,totalHits:t}=await v(y,s);x(e,t)}catch{f("Failed to load images. Please try again later.")}finally{M()}}function x(e,t){if(s===1&&(u=t,!u)){f("Sorry, there are no images matching your search query. Please try again!");return}$(e,l),O.refresh(),B(e),s>1&&P()}function B(e){if(!a)return;const t=e.length===40&&s*40<u;a.style.display=t?"block":"none",!t&&s*40>=u&&f("We're sorry, but you've reached the end of search results.")}function D(){a&&(a.style.display="none")}
//# sourceMappingURL=index.js.map
