import{a as h,S as m}from"./assets/vendor-CMnfnrHK.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const p="https://pixabay.com/api/",y="48986485-6ea1696c08190fb3e366663c0";async function d(o,e=1,s=40){try{return(await h.get(p,{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:s}})).data}catch(r){throw console.error("Error fetching images:",r),r}}function u(o){const e=document.querySelector(".gallery");if(!e)return;const s=o.map(r=>`
        <a class="gallery_item" href="${r.largeImageURL}">
          <img class="gallery_image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${r.likes}</p>
            <p class="info-item"><b>Views:</b> ${r.views}</p>
            <p class="info-item"><b>Comments:</b> ${r.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </a>
      `).join("");e.insertAdjacentHTML("beforeend",s)}const g=document.querySelector(".form"),L=document.querySelector(".input"),w=document.querySelector(".load-more");let n=1,i="";const c=40;let f=new m(".gallery a");g.addEventListener("submit",async o=>{if(o.preventDefault(),i=L.value.trim(),!!i){n=1,clearGallery(),hideLoadMoreButton(),showLoader();try{const e=await d(i,n,c);if(e.hits.length===0){alert("No images found. Try another query!"),hideLoader();return}u(e.hits),f.refresh(),hideLoader(),e.totalHits>c&&showLoadMoreButton()}catch(e){console.error("Error:",e),alert("Something went wrong. Please try again."),hideLoader()}}});w.addEventListener("click",async()=>{n+=1,hideLoadMoreButton(),showLoader();try{const o=await d(i,n,c);u(o.hits),f.refresh(),hideLoader();const e=Math.ceil(o.totalHits/c);n>=e?(hideLoadMoreButton(),alert("We're sorry, but you've reached the end of search results.")):showLoadMoreButton(),b()}catch(o){console.error("Error:",o),alert("Something went wrong. Please try again."),hideLoader()}});function b(){const o=document.querySelector(".gallery_item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
