import{a as L,i as S,S as w}from"./assets/vendor-DnVuFECx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const q="https://pixabay.com/api/",v="48986485-6ea1696c08190fb3e366663c0";async function M(e,t=1,n=40){try{return(await L.get(q,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:n}})).data}catch(a){throw console.error("Error fetching images:",a),a}}function P(e,t){if(!e||e.length===0){u("No images found!");return}const n=e.map(({webformatURL:a,largeImageURL:o,tags:r,likes:c,views:p,comments:g,downloads:b})=>`
    <a class="gallery-item" href="${o}" data-title="${r}">
      <img src="${a}" alt="${r}" loading="lazy"/>
      <div class="info">
        <p><b>Likes:</b> ${c}</p>
        <p><b>Views:</b> ${p}</p>
        <p><b>Comments:</b> ${g}</p>
        <p><b>Downloads:</b> ${b}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n)}function u(e,t="topRight"){try{S.show({message:e,position:t,timeout:3e3})}catch(n){console.error("Error displaying notification:",n)}}function $(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function B(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function E(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function f(e){const t=document.querySelector(".load-more");t&&(t.style.display=e?"block":"none",e&&t.scrollIntoView({behavior:"smooth",block:"end"}))}let d="",i=1,s=0;const l=40,I=document.querySelector(".form"),y=document.querySelector(".gallery"),m=document.querySelector(".load-more"),O=new w(".gallery a",{captionsData:"alt",captionDelay:250});I.addEventListener("submit",A);m.addEventListener("click",N);function A(e){e.preventDefault(),d=e.currentTarget.elements.query.value.trim(),d&&(i=1,s=0,H(),m.style.display="none",h())}function H(){i=1,s=0,y.innerHTML=""}function N(){i++,h(),$()}async function h(){B(),f(!1);try{const{hits:e,totalHits:t}=await M(d,i,l);x(e,t)}catch{u("Failed to load images. Please try again later.")}finally{E()}}function x(e,t,n){if(i===1&&(s=t,!s)){u("Sorry, there are no images matching your search query. Please try again!");return}P(e,y),O.refresh(),D(e)}function D(e){const t=e.length===l&&i*l<s;f(t),!t&&i*l>=s&&u("We're sorry, but you've reached the end of search results.")}
//# sourceMappingURL=index.js.map
